const data = [
  {
    id: "1",
    unique_id: "574ed359ce2e18.82356240",
    supplier_unique_id: "5887d0173e8596.00000000",
    product_author: "G. K. CHESTERTON",
    product_name: "The Man Who Was Thursday",
    product_category: "books",
    product_description:
      "In Edwardian era London, Gabriel Syme is recruited at Scotland Yard to a secret anti-anarchist police corps. Lucian Gregory, an anarchistic poet, lives in the suburb of Saffron Park. Syme meets him at a party and they debate the meaning of poetry. Gregory argues that revolt is the basis of poetry. Syme demurs, insisting the essence of poetry is not revolution but law. He antagonises Gregory by asserting that the most poetical of human creations is the timetable for the London Underground.",
    unit_price: "10.00",
    stock: "8",
    url: "product/the-man-who-was-thursday",
    cover_photo_url: "uploads/cover_photo/574ed359ce2e18.82356240.png",
    datetime_created: "2019-11-25 09:01:09",
  },
  {
    id: "2",
    unique_id: "574ed359ce2e18.82356121",
    supplier_unique_id: "5887d0173e8596.00000000",
    product_author: "C.S. LEWIS",
    product_name: "The Greatest Divorce",
    product_category: "books",
    product_description:
      'The Great Divorce is a novel by the British author C. S. Lewis, published in 1945, and based on a theological dream vision of his in which he reflects on the Christian conceptions of Heaven and Hell.\r\n\r\nThe narrator inexplicably finds himself in a grim and joyless city, the "grey town", where it rains continuously, even indoors, which is either Hell or Purgatory depending on whether or not one stays there. He eventually finds a bus-stop for those who desire an excursion to some other place (the destination later turns out to be the foothills of Heaven). He waits in line for the bus and listens to the arguments between his fellow passengers. As they await the bus\' arrival, many of them quit the line in disgust before the bus pulls up. When it arrives, the bus driver is an angel. Once the few remaining passengers have boarded, the bus flies upward, off the pavement into the grey, rainy sky.',
    unit_price: "12.00",
    stock: "7",
    url: "product/the-greatest-divorce",
    cover_photo_url: "uploads/cover_photo/574ed359ce2e18.82356121.png",
    datetime_created: "2019-11-25 09:56:03",
  },
  {
    id: "3",
    unique_id: "5887d0173e8596.49997722",
    supplier_unique_id: "5887d0173e8596.00000000",
    product_author: "L. CARRINGTON GOODRICH",
    product_name: "A Short History of the Chinese People",
    product_category: "books",
    product_description:
      "This survey begins with the prehistoric period, then discusses the major currents of Chinese history, philosophy, culture and politics -- from the reigns of such dynastic rulers as the Shang to the era of Mongol conquests and the Manchu dynasties, culminating with the birth of the Chinese Republic in 1912. 17 maps, 24 illustrations.",
    unit_price: "10.00",
    stock: "8",
    url: "product/a-short-history-of-the-chinese-people",
    cover_photo_url: "uploads/cover_photo/5887d0173e8596.49997722.png",
    datetime_created: "2019-11-25 09:00:44",
  },
  {
    id: "4",
    unique_id: "574ed359ce2e18.82356123",
    supplier_unique_id: "5887d0173e8596.00000000",
    product_author: "Watty Piper",
    product_name: "The Little Train That Could",
    product_category: "books",
    product_description:
      'The Little Engine That Could is an American fairytale (existing in the form of several illustrated children\'s books and movies) that became widely known in the United States after publication in 1930 by Platt & Munk. The story is used to teach children the value of optimism and hard work. Based on a 2007 online poll, the National Education Association named the book one of its "Teachers\' Top 100 Books for Children".[1] A 1949 recording of the story was inducted to the National Recording Registry in 2009.\r\n\r\nIn the tale, a long train must be pulled over a high mountain after its engine breaks down. Larger engines, treated anthropomorphically, are asked to pull the train; for various reasons they refuse. The request is sent to a small engine, who agrees to try. The engine succeeds in pulling the train over the mountain while repeating its motto: "I-think-I-can".',
    unit_price: "10.00",
    stock: "8",
    url: "product/the-little-train-that-could",
    cover_photo_url: "uploads/cover_photo/574ed359ce2e18.82356123.png",
    datetime_created: "2019-11-25 09:01:03",
  },
  {
    id: "6",
    unique_id: "574ed359ce2e18.82356495",
    supplier_unique_id: "5887d0173e8596.00000000",
    product_author: "F. Scott Fitzgerald",
    product_name: "The Great Gatsby",
    product_category: "books",
    product_description:
      "The Great Gatsby is a 1925 novel written by American author F. Scott Fitzgerald that follows a cast of characters living in the fictional towns of West Egg and East Egg on prosperous Long Island in the summer of 1922. The story primarily concerns the young and mysterious millionaire Jay Gatsby and his quixotic passion and obsession with the beautiful former debutante Daisy Buchanan. Considered to be Fitzgerald's magnum opus, The Great Gatsby explores themes of decadence, idealism, resistance to change, social upheaval and excess, creating a portrait of the Roaring Twenties that has been described as a cautionary[a] tale regarding the American Dream.",
    unit_price: "25.00",
    stock: "8",
    url: "product/the-great-gatsby",
    cover_photo_url: "uploads/cover_photo/574ed359ce2e18.82356495.png",
    datetime_created: "2019-11-25 09:00:55",
  },
  {
    id: "7",
    unique_id: "5887d0173e8596.49997726",
    supplier_unique_id: "5887d0173e8596.00000000",
    product_author: "William Shakespeare",
    product_name: "The Merchant of Venice",
    product_category: "books",
    product_description:
      "The Merchant of Venice is a 16th-century play written by William Shakespeare in which a merchant in Venice named Antonio must default on a large loan provided by a Jewish moneylender, Shylock. It is believed to have been written between 1596 and 1599.\r\n\r\nBassanio, a young Venetian of noble rank, wishes to woo the beautiful and wealthy heiress Portia of Belmont. Having squandered his estate, he needs 3,000 ducats to subsidise his expenditures as a suitor. Bassanio approaches his friend Antonio, a wealthy merchant of Venice who has previously and repeatedly bailed him out. Antonio agrees, but since he is cash-poor \u2013 his ships and merchandise are busy at sea to Tripolis, the Indies, Mexico and England \u2013 he promises to cover a bond if Bassanio can find a lender, so Bassanio turns to the Jewish moneylender Shylock and names Antonio as the loan's guarantor.",
    unit_price: "23.00",
    stock: "8",
    url: "product/the-merchant-of-venice",
    cover_photo_url: "uploads/cover_photo/5887d0173e8596.49997726.png",
    datetime_created: "2019-11-25 09:01:15",
  },
  {
    id: "8",
    unique_id: "574ed359ce2e18.82356497",
    supplier_unique_id: "5887d0173e8596.00000000",
    product_author: "Oswald J. Smith",
    product_name: "The Man God Uses",
    product_category: "books",
    product_description:
      "Nothing is more needed in the Church to-day then a clear, concise, and Scriptural plea for separation, Spirit-filling and service, says Dr.R. E. Neighbour.\r\n\r\nThe blessed truths of the Spirit-filled life are open to all the saved. This book does not concede Christianity as a creed to be memorised and carefully shelved for Sunday worship. It conceives Christianity as a life created by and centred in the Lord Jesus Christ, for use in a world steeped in sin but sought by One mighty to save. It is a book that should be read and translated into Christian life and service.",
    unit_price: "26.50",
    stock: "8",
    url: "product/the-man-god-uses",
    cover_photo_url: "uploads/cover_photo/574ed359ce2e18.82356497.png",
    datetime_created: "2019-11-25 09:01:06",
  },
];

module.export = data